### ISSUE TITLE
Regression: import error

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore-validation#21]
Json files cannot be created. The following error is shown by GitHub Actions @seanbudd 
>     from .majorMinorPatch import MajorMinorPatch
67
ImportError: attempted relative import with no known parent package

**Comment by seanbudd** [comment]
Closed via 7563382db7a7b7779181088c252fcb355b1e0837 and f4718fd4c08c1bb60bfdc1fdbb6b4ce6080c645a
