### ISSUE TITLE
When add-on publication date is added, the json file is not valid

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore-validation#39]
### Steps to reproduce

- Install the  last version ofWindows App Essential submitted today by @josephsl in latest alpha of NVDA.
- Open the add-on store and browse add-ons
- See the log when Windows App Essential is selected.
- In your local computer, edit the json file adding a submission time manually
- Run again NVDA and open the store,to see that the error is fixed.

I think that somekindof encoding error is produced when creating the json file.
-

**Comment by nvdaes** [comment]
Sorry, the issue seems to be in NVDA implementation: submissionTime has to be divided by 1000 in NVDA. I'lltest this locally with the wintenApps.json fileincluded in the store, and ifthis works I'll create a PR to fixup this.I think that creating a new issue in NVDA is not needed for this obvious error.
I'll mention this issue.

**Comment by nvdaes** [comment]
Though another approach is to make the division in this repo.
I'llwait for @seanbudd thoughts.
If this repo is changed, wintenApps latest version should be replaced.

**Comment by nvdaes** [comment]
In fact, testing with NVDA dividing the submission time of Windows App Essential with // 1000, the issue is fixed. In this repo, we are multiplying the timestamp with * 1000. We may try to remove this and submit some add-on for testing.

**Comment by seanbudd** [comment]
At this stage, the code is in the submission process. I would encourage making the fix in NVDA as appropriate

**Comment by nvdaes** [comment]
I've created nvaccess/nvda#17193 PR. I'll mark this as ready for review since all checks pass locally.
