### ISSUE TITLE
Currently used channel names don't match what is  used in the add-ons template

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/addon-datastore-validation#6]
Currently validation code seems to expect add-on channel to be either "beta" or "stable" whereas add-ons template explicitly states that for stable add-ons channels should be `None` and for development releases "dev" is an appropriate channel name. Is this discrepancy intentional - if so what are the reasons for this change? My main concern with this is that you seems to allow submitting add-ons for the older versions of NVDA which expects the old naming scheme for the channels.

**Comment by lukaszgo1** [comment]
@feerrenrut  @seanbudd  Have you seen this?

**Comment by seanbudd** [comment]
Could you link to a file where this usage is happening?
Most (all?) usages of `stable|beta`, are in the context of the addon metadata `.json` files, which are not used in any NVDA production systems right now.

**Comment by lukaszgo1** [comment]
Obviously these usages are not in the production yet what I am asking about is why they differ from channel names are used in production at present. Current definition of channels in add-on template can be found [here](https://github.com/nvdaaddons/AddonTemplate/blob/master/buildVars.py)

**Comment by feerrenrut** [comment]
This isn't an issue. We were aware that some addon's may have different values for channel names, however there is no officially accepted key / value for channel in the manifest (as accepted by NVDA)

Requiring channel in the manifest would be backwards incompatible. As you noted, we want to support older addon versions that may have a different set of values, or no value at all. Thus we'll be tracking the channel for add-ons outside of the manifest when the add-on store is integrated with NVDA. This is also important for comparing version numbers of an installed add-on.

**Comment by feerrenrut** [comment]
Here is the official spec for an addon manifest: https://github.com/nvaccess/nvda/blob/master/source/addonHandler/__init__.py#L694

**Comment by lukaszgo1** [comment]
Okay, I understand now. Since for most manifest values you're ensuring that what is in the JSON file matches values from the manifest my assumption was that the same would be done for the channel but I obviously didn't read the code. Sorry for the noise!
